# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 05:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Optica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='opticas/images', verbose_name='Imagen')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección')),
                ('url', models.URLField(verbose_name='Link')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opticas', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
        ),
    ]
