# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'ordering': ['-created_at'],
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='opticas/images', verbose_name='Imagen')),
                ('url', models.URLField(verbose_name='Link')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='services.Category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'ordering': ['-created_at'],
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='StoreHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Almacén',
                'ordering': ['-created_at'],
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.AlterModelOptions(
            name='optica',
            options={'ordering': ['-created_at'], 'verbose_name': 'Óptica', 'verbose_name_plural': 'Ópticas'},
        ),
        migrations.AddField(
            model_name='storehouse',
            name='optica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storehouses', to='services.Optica', verbose_name='Óptica'),
        ),
        migrations.AddField(
            model_name='storehouse',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storehouses', to='services.Product', verbose_name='Producto'),
        ),
        migrations.AlterUniqueTogether(
            name='storehouse',
            unique_together=set([('product', 'optica')]),
        ),
    ]
