# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170627_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optica',
            name='image',
            field=models.ImageField(upload_to='images/opticas', verbose_name='Imagen'),
        ),
    ]
