# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20170627_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optica',
            name='image',
        ),
    ]
