# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_optica_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='optica',
            name='image',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Imagen'),
        ),
    ]
