# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20170628_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Distritos',
                'ordering': ['-created_at'],
                'verbose_name': 'Distrito',
            },
        ),
        migrations.AddField(
            model_name='optica',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opticas', to='services.District', verbose_name='Distrito'),
        ),
    ]
