# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_product_optica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='images_promotions', verbose_name='Imagen')),
                ('url', models.URLField(verbose_name='Link')),
                ('optica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='services.Optica', verbose_name='Óptica')),
            ],
            options={
                'verbose_name_plural': 'Promociones',
                'ordering': ['-created_at'],
                'verbose_name': 'Promoción',
            },
        ),
    ]
