# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='Habilitada'),
        ),
    ]
