# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20170629_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
