# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20171031_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='optica',
        ),
    ]
