# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_remove_product_optica'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=2, max_length=50, verbose_name='Marca'),
            preserve_default=False,
        ),
    ]
