# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0015_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(null=True, upload_to='images_sedes', verbose_name='Imagen')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección')),
                ('url', models.URLField(verbose_name='Link')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='services.District', verbose_name='Distrito')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='optica',
            name='district',
        ),
        migrations.RemoveField(
            model_name='optica',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='optica',
        ),
        migrations.DeleteModel(
            name='Optica',
        ),
        migrations.AddField(
            model_name='promotion',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='services.Sede', verbose_name='Sede'),
        ),
    ]
