# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-16 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20171101_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='services.Category', verbose_name='Categoría'),
            preserve_default=False,
        ),
    ]
